#!/usr/bin/env bash
#Install nginx on your web-01
apt-get -y update
apt-get -y install nginx
sudo chown  $USER:$USER /var/www/html/index.html
echo "Hello World!" > /var/www/html/index.html
service nginx restart
