#!/usr/bin/env bash

# Ensure Nginx is installed (in case this script runs independently)
sudo apt install nginx -y

# Create the redirect rule in the Nginx configuration
echo "rewrite ^/redirect_me$ http://google.com permanent;" | sudo tee -a /etc/nginx/sites-available/default

# Reload Nginx to apply the changes
sudo service nginx reload
