#!/usr/bin/env bash
# install and configure HAproxy on your lb-01 server.
sudo apt update && sudo apt upgrade
sudo apt-get -y install haproxy
sudo chown  $USER:$USER /etc/haproxy/haproxy.cfg
echo "
frontend estebanweb
    bind *:80
    mode http
    default_backend app
backend app
    balance roundrobin
    server 510439-web-01 54.208.60.238:80 check
    server 510439-web-02 100.26.56.29:80 check" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
