#!/usr/bin/env bash
# Nginx must be running, and listening on port 80 of all the server’s active IPv4 IPs

sudo sed -i '/listen\s*80;/!s/listen\s*443 ssl;/listen 80;/g' /etc/nginx/sites-available/default
sudo systemctl restart nginx
