#!/usr/bin/env bash
# fix this container so that Nginx is running as the nginx user.

# Modify Nginx configuration to run as nginx user
sed -i 's/user\s*nginx;/user nginx;/' /etc/nginx/nginx.conf

# Adjust Nginx configuration to listen on all active IPs on port 8080
sed -i 's/listen\s*80;/listen *:8080;/' /etc/nginx/sites-available/default

# Restart Nginx service to apply changes
service nginx restart
